{
 "title": "Qdrant",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Collections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "collections_total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "collections_total", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "collections_aggregated_total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "collections_aggregated_total", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Collection vector",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "collections_vector_total", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Collection vectors total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "sum(collections_vector_total)", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "collections_full_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "expr": "collections_full_total", "legendFormat": "{{host}}" }
   ]
  },
  { "title": "gRPC API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "gRPC API responses duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "grpc_responses_avg_duration_seconds",
     "legendFormat": "{{ host }} avg"
    },
    {
     "expr": "grpc_responses_min_duration_seconds",
     "legendFormat": "{{host}} min"
    },
    {
     "expr": "grpc_responses_max_duration_seconds",
     "legendFormat": "{{host}} max"
    }
   ]
  },
  {
   "title": "gRPC API RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg(irate(grpc_responses_total[1m]))",
     "legendFormat": "success"
    },
    {
     "expr": "avg(irate(grpc_responses_fail_total[1m]))",
     "legendFormat": "failed"
    }
   ]
  },
  { "title": "REST API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "REST API responses duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "rest_responses_avg_duration_seconds",
     "legendFormat": "{{host}} avg"
    },
    {
     "expr": "rest_responses_min_duration_seconds",
     "legendFormat": "{{host}} min"
    },
    {
     "expr": "rest_responses_max_duration_seconds",
     "legendFormat": "{{host}} max"
    }
   ]
  },
  {
   "title": "REST API RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "avg(irate(rest_responses_total[1m]))",
     "legendFormat": "success"
    },
    {
     "expr": "avg(irate(rest_responses_fail_total[1m]))",
     "legendFormat": "failed"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "cluster_enabled",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "expr": "cluster_enabled", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "cluster_pending_operations_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "cluster_pending_operations_total",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "cluster_voter",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cluster_voter", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "cluster_peers_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "cluster_peers_total", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "cluster_term",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
   "targets": [
    { "expr": "cluster_term", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "cluster_commit",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cluster_commit", "legendFormat": "{{host}}" }
   ]
  }
 ]
}